/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_prismatic_kotlinangle */

#ifndef _Included_org_prismatic_kotlinangle
#define _Included_org_prismatic_kotlinangle
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_org_prismatic_kotlinangle_AngleNative_testCallingAngle
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_org_prismatic_kotlinangle_AngleNative_createPrismAngle
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_org_prismatic_kotlinangle_AngleNative_fillScreenRGBAngle
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

JNIEXPORT jint JNICALL Java_org_prismatic_kotlinangle_AngleNative_makeAngleContextCurrent
  (JNIEnv * , jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
