/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_prismatic_prismangle_PrismAngle */

#ifndef _Included_org_prismatic_prismangle_PrismAngle
#define _Included_org_prismatic_prismangle_PrismAngle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_prismatic_prismangle_PrismAngle
 * Method:    testCallingAngle
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_org_prismatic_AngleNative_testCallingAngle
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_org_prismatic_AngleNative_createPrismAngle
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_org_prismatic_AngleNative_fillScreenRGBAngle
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
